# Generated by Django 4.2.6 on 2023-10-27 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0003_reader'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.UUIDField(default=uuid.UUID('59597484-5a26-4e96-b0a2-345c0df845ee'), primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.reader')),
            ],
        ),
    ]
