# Generated by Django 4.2.6 on 2023-10-30 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_id',
            field=models.UUIDField(default=uuid.UUID('93d37e44-3e38-4860-976f-6712b15d767b'), primary_key=True, serialize=False, unique=True),
        ),
    ]
