# Generated by Django 4.2.6 on 2023-12-04 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_alter_bookmark_bookmark_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_id',
            field=models.UUIDField(default=uuid.UUID('04fbe6f6-c73e-427c-a982-c7f100e5c4df'), primary_key=True, serialize=False),
        ),
    ]
