# Generated by Django 4.2.6 on 2023-12-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
