# Generated by Django 4.2.6 on 2023-12-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/blank_profile.png', null=True, upload_to='profile/'),
        ),
    ]
