# Generated by Django 4.2.6 on 2023-10-25 05:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0003_reader'),
        ('publish', '0002_rename_image_file_book_book_cover_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('forum_title', models.CharField(max_length=256)),
                ('num_comments', models.IntegerField(default=0, editable=False)),
                ('book_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.book')),
                ('forum_creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.reader')),
            ],
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('reply_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('date_uploaded', models.DateTimeField(editable=False)),
                ('commentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.reader')),
                ('forum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum')),
            ],
        ),
    ]
