# Generated by Django 4.2.6 on 2023-10-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forum_book_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='forum_discussion',
            field=models.TextField(null=True),
        ),
    ]
