# Generated by Django 4.2.6 on 2023-10-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_reader'),
        ('forum', '0003_forum_forum_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumreply',
            name='commentor_id',
        ),
        migrations.AddField(
            model_name='forumreply',
            name='commentor_reader_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auths.reader'),
        ),
    ]
