# Generated by Django 4.2.6 on 2023-10-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_forumreply_commentor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumreply',
            old_name='commentor_reader_id',
            new_name='commentor_id',
        ),
    ]
