# Generated by Django 4.2.6 on 2023-10-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_file',
            new_name='book_cover_file',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image_link',
            new_name='book_cover_link',
        ),
        migrations.AlterField(
            model_name='book',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_rating',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
