# Generated by Django 4.2.6 on 2023-10-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forum_book_topic'),
        ('publish', '0002_rename_image_file_book_book_cover_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
